name: Backport

on:
  pull_request_target:
    types: ["labeled", "closed"]

permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
  
jobs:
  backport:
    name: Backport PR
    if: >
      github.event.pull_request.merged &&
      (
        (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'backport')) ||
        (github.event.action == 'labeled' && contains(github.event.label.name, 'backport'))
      )
    runs-on: ubuntu-latest
    steps:
      - name: Backport Action
        uses: sorenlouv/backport-github-action@v9.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_backport_label_prefix: backport/

      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log
        
      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log        
          